name: eunoia_chat_application
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.6
  cupertino_icons: 1.0.6
  dartz: 0.10.1
  equatable: 2.0.5
  flutter_easyloading: 3.0.5
  flutter_dotenv: 5.1.0
  shared_preferences: 2.3.2
  cached_network_image: 3.4.1
  get_it: 8.0.0
  google_fonts: 6.2.1
  dio: 5.7.0
  flash: 3.1.1
  flutter_svg: 2.0.10
  supabase_flutter: 2.8.0
  go_router: 14.3.0
  rxdart: 0.28.0
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  realtime_client: 2.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: 3.0.0


flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    


