// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdBN9wTXxSZTImNMahQ6khAczM_YhkFVc',
    appId: '1:822739428794:web:ebbfb59f0b4317b74f6983',
    messagingSenderId: '822739428794',
    projectId: 'eunoia-chat',
    authDomain: 'eunoia-chat.firebaseapp.com',
    storageBucket: 'eunoia-chat.firebasestorage.app',
    measurementId: 'G-1PG14CCB00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx4Vsn0uQGbO9w_hNX3TgxK2fIjFD8zyM',
    appId: '1:822739428794:android:7cf1f5d929bafa9e4f6983',
    messagingSenderId: '822739428794',
    projectId: 'eunoia-chat',
    storageBucket: 'eunoia-chat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUmFwYopkKauSawcljKwWQnePZQ2ctoQ0',
    appId: '1:822739428794:ios:d09e76c671c629f74f6983',
    messagingSenderId: '822739428794',
    projectId: 'eunoia-chat',
    storageBucket: 'eunoia-chat.firebasestorage.app',
    iosBundleId: 'com.eunoia.eunoiachat',
  );
}
